// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetAdoption.Api.Data;

#nullable disable

namespace PetAdoption.Api.Data.Migrations
{
    [DbContext(typeof(PetContext))]
    [Migration("20240908140517_Initalsss")]
    partial class Initalsss
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetAdoption.Api.Data.Entities.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdoptionStatus")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdoptionStatus = 0,
                            Breed = "Dog - Golden Retriever",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Buddy is a friendly and playful Golden Retriever, known for being great with kids.",
                            Gender = 0,
                            Image = "wwwroot/images/pets/img_1.jpg",
                            IsActive = false,
                            Name = "Buddy",
                            Price = 300.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 2,
                            AdoptionStatus = 0,
                            Breed = "Cat - Persian",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mittens is a calm and affectionate Persian cat.",
                            Gender = 0,
                            Image = "wwwroot/images/pets/img_2.jpg",
                            IsActive = false,
                            Name = "Mittens",
                            Price = 200.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 3,
                            AdoptionStatus = 0,
                            Breed = "Dog - Beagle",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Charlie is an energetic Beagle who loves to explore.",
                            Gender = 0,
                            Image = "wwwroot/images/pets/img_3.jpg",
                            IsActive = false,
                            Name = "Charlie",
                            Price = 250.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 4,
                            AdoptionStatus = 0,
                            Breed = "Cat - Siamese",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Whiskers is a vocal and curious Siamese cat.",
                            Gender = 0,
                            Image = "wwwroot/images/pets/img_4.jpg",
                            IsActive = false,
                            Name = "Whiskers",
                            Price = 180.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 5,
                            AdoptionStatus = 0,
                            Breed = "Dog - Labrador Retriever",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Max is a loyal Labrador Retriever who loves to fetch.",
                            Gender = 0,
                            Image = "wwwroot/images/pets/img_5.jpg",
                            IsActive = false,
                            Name = "Max",
                            Price = 350.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 6,
                            AdoptionStatus = 0,
                            Breed = "Dog - Poodle",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bella is an elegant Poodle who enjoys attention.",
                            Gender = 0,
                            Image = "wwwroot/images/pets/img_6.jpg",
                            IsActive = false,
                            Name = "Bella",
                            Price = 300.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 7,
                            AdoptionStatus = 0,
                            Breed = "Cat - Ragdoll",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Luna is a gentle Ragdoll cat who loves to cuddle.",
                            Gender = 0,
                            Image = "wwwroot/images/pets/img_7.jpg",
                            IsActive = false,
                            Name = "Luna",
                            Price = 250.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 8,
                            AdoptionStatus = 0,
                            Breed = "Dog - Boxer",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rocky is a strong Boxer who loves to play.",
                            Gender = 0,
                            Image = "wwwroot/images/pets/img_8.jpg",
                            IsActive = false,
                            Name = "Rocky",
                            Price = 320.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 9,
                            AdoptionStatus = 0,
                            Breed = "Cat - British Shorthair",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Shadow is a quiet British Shorthair who enjoys solitude.",
                            Gender = 0,
                            Image = "wwwroot/images/pets/img_9.jpg",
                            IsActive = false,
                            Name = "Shadow",
                            Price = 220.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 10,
                            AdoptionStatus = 0,
                            Breed = "Dog - Dachshund",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Oscar is a curious Dachshund who loves to dig.",
                            Gender = 0,
                            Image = "wwwroot/images/pets/img_10.jpg",
                            IsActive = false,
                            Name = "Oscar",
                            Price = 200.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 11,
                            AdoptionStatus = 0,
                            Breed = "Cat - Bengal",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cleo is an active Bengal cat who loves to climb.",
                            Gender = 0,
                            Image = "wwwroot/images/pets/img_11.jpg",
                            IsActive = false,
                            Name = "Cleo",
                            Price = 300.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 12,
                            AdoptionStatus = 0,
                            Breed = "Dog - Shih Tzu",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Daisy is a sweet Shih Tzu who enjoys being pampered.",
                            Gender = 0,
                            Image = "wwwroot/images/pets/img_12.jpg",
                            IsActive = false,
                            Name = "Daisy",
                            Price = 220.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 13,
                            AdoptionStatus = 0,
                            Breed = "Cat - Maine Coon",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Simba is a large Maine Coon with a gentle disposition.",
                            Gender = 0,
                            Image = "wwwroot/images/pets/img_13.jpg",
                            IsActive = false,
                            Name = "Simba",
                            Price = 350.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 14,
                            AdoptionStatus = 0,
                            Breed = "Dog - Border Collie",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Jack is an intelligent Border Collie who loves to work.",
                            Gender = 0,
                            Image = "wwwroot/images/pets/img_14.jpg",
                            IsActive = false,
                            Name = "Jack",
                            Price = 320.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 15,
                            AdoptionStatus = 0,
                            Breed = "Cat - Scottish Fold",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nala is a playful Scottish Fold with a unique look.",
                            Gender = 0,
                            Image = "wwwroot/images/pets/img_15.jpg",
                            IsActive = false,
                            Name = "Nala",
                            Price = 280.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 16,
                            AdoptionStatus = 0,
                            Breed = "Dog - German Shepherd",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Zeus is a protective German Shepherd who is very loyal.",
                            Gender = 0,
                            Image = "wwwroot/images/pets/img_16.jpg",
                            IsActive = false,
                            Name = "Zeus",
                            Price = 400.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 17,
                            AdoptionStatus = 0,
                            Breed = "Dog - Cocker Spaniel",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Milo is a friendly Cocker Spaniel with a lot of energy.",
                            Gender = 0,
                            Image = "wwwroot/images/pets/img_17.jpg",
                            IsActive = false,
                            Name = "Milo",
                            Price = 280.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 18,
                            AdoptionStatus = 0,
                            Breed = "Cat - Exotic Shorthair",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mochi is a calm Exotic Shorthair who enjoys lounging.",
                            Gender = 0,
                            Image = "wwwroot/images/pets/img_18.jpg",
                            IsActive = false,
                            Name = "Mochi",
                            Price = 250.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 19,
                            AdoptionStatus = 0,
                            Breed = "Dog - Pomeranian",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bailey is a lively Pomeranian who loves to be the center of attention.",
                            Gender = 0,
                            Image = "wwwroot/images/pets/img_19.jpg",
                            IsActive = false,
                            Name = "Bailey",
                            Price = 300.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 20,
                            AdoptionStatus = 0,
                            Breed = "Cat - Abyssinian",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Oliver is a curious Abyssinian who loves to explore.",
                            Gender = 0,
                            Image = "wwwroot/images/pets/img_20.jpg",
                            IsActive = false,
                            Name = "Oliver",
                            Price = 240.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 21,
                            AdoptionStatus = 0,
                            Breed = "Dog - Redbone Coonhound",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rusty is an active Redbone Coonhound who loves to run.",
                            Gender = 0,
                            Image = "wwwroot/images/pets/img_21.jpg",
                            IsActive = false,
                            Name = "Rusty",
                            Price = 270.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 22,
                            AdoptionStatus = 0,
                            Breed = "Cat - Sphynx",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Zoe is a hairless Sphynx with a very affectionate personality.",
                            Gender = 0,
                            Image = "wwwroot/images/pets/img_22.jpg",
                            IsActive = false,
                            Name = "Zoe",
                            Price = 320.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 23,
                            AdoptionStatus = 0,
                            Breed = "Dog - Australian Shepherd",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Finn is an energetic Australian Shepherd who loves to herd.",
                            Gender = 0,
                            Image = "wwwroot/images/pets/img_23.jpg",
                            IsActive = false,
                            Name = "Finn",
                            Price = 350.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 24,
                            AdoptionStatus = 0,
                            Breed = "Cat - Burmese",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lily is a vocal Burmese cat who enjoys human company.",
                            Gender = 0,
                            Image = "wwwroot/images/pets/img_24.jpg",
                            IsActive = false,
                            Name = "Lily",
                            Price = 280.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 25,
                            AdoptionStatus = 0,
                            Breed = "Dog - Rottweiler",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rex is a strong Rottweiler who is very protective.",
                            Gender = 0,
                            Image = "wwwroot/images/pets/img_25.jpg",
                            IsActive = false,
                            Name = "Rex",
                            Price = 380.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 26,
                            AdoptionStatus = 0,
                            Breed = "Cat - Norwegian Forest",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chloe is a fluffy Norwegian Forest cat who loves the outdoors.",
                            Gender = 0,
                            Image = "wwwroot/images/pets/img_26.jpg",
                            IsActive = false,
                            Name = "Chloe",
                            Price = 320.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 27,
                            AdoptionStatus = 0,
                            Breed = "Dog - Cavalier King Charles Spaniel",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ginger is a gentle Cavalier King Charles Spaniel who loves to cuddle.",
                            Gender = 0,
                            Image = "wwwroot/images/pets/img_27.jpg",
                            IsActive = false,
                            Name = "Ginger",
                            Price = 330.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 28,
                            AdoptionStatus = 0,
                            Breed = "Dog - Shiba Inu",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Toby is an independent Shiba Inu with a lot of personality.",
                            Gender = 0,
                            Image = "wwwroot/images/pets/img_28.jpg",
                            IsActive = false,
                            Name = "Toby",
                            Price = 340.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 29,
                            AdoptionStatus = 0,
                            Breed = "Cat - Russian Blue",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sasha is a reserved Russian Blue who enjoys quiet environments.",
                            Gender = 0,
                            Image = "wwwroot/images/pets/img_29.jpg",
                            IsActive = false,
                            Name = "Sasha",
                            Price = 300.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 30,
                            AdoptionStatus = 0,
                            Breed = "Dog - Bulldog",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bruno is a strong Bulldog with a gentle heart",
                            Gender = 0,
                            Image = "wwwroot/images/pets/img_30.jpg",
                            IsActive = false,
                            Name = "Bruno",
                            Price = 350.0,
                            Views = 0
                        });
                });

            modelBuilder.Entity("PetAdoption.Api.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PetAdoption.Api.Data.Entities.UserAdoption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdoptedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAdoptions");
                });

            modelBuilder.Entity("PetAdoption.Api.Data.Entities.UserFavorites", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PetId");

                    b.HasIndex("PetId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("PetAdoption.Api.Data.Entities.UserAdoption", b =>
                {
                    b.HasOne("PetAdoption.Api.Data.Entities.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetAdoption.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetAdoption.Api.Data.Entities.UserFavorites", b =>
                {
                    b.HasOne("PetAdoption.Api.Data.Entities.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetAdoption.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
